"""Emit a regex-derived replacement for `zero_shot_findings_disease_cls.csv`.

Stanford's file is itself regex output — their own documentation says so:

    "These labels were generated by applying regex-based matching of zero-shot
     positive and negative prompts to the findings section; therefore, some
     entries marked as missing may in fact correspond to positive or negative
     cases but remain missing when the prompt is not explicitly stated."

So this is a like-for-like replacement, not a change of method: the same 31
columns and the same `1 / 0 / -1` encoding, produced by the rules in this
package instead of the undisclosed original prompts.

Two files are written, because the 3-value encoding is lossy:

* `zero_shot_findings_regex.csv`      — drop-in, identical schema to Stanford's
* `zero_shot_findings_regex_full.csv` — the same labels before flattening,
                                        keeping all five assertion states

`pancreatic_atrophy` comes from `panc_atrophy`, i.e. matched **inside the
pancreas context only** — unlike the other 29, whose terms are self-identifying.
"""
from __future__ import annotations

import pandas as pd

from . import assertion as A
from . import config as C

# Stanford's column order, reproduced exactly so the file is a drop-in.
COLUMNS = [
    "study_id", "submucosal_edema", "renal_hypodensities", "aortic_valve_calcification",
    "coronary_calcification", "thrombosis", "metastatic_disease", "pancreatic_atrophy",
    "renal_cyst", "osteopenia", "surgically_absent_gallbladder", "atelectasis",
    "abdominal_aortic_aneurysm", "anasarca", "hiatal_hernia", "lymphadenopathy",
    "prostatomegaly", "biliary_ductal_dilation", "cardiomegaly", "splenomegaly",
    "hepatomegaly", "atherosclerosis", "ascites", "pleural_effusion", "hepatic_steatosis",
    "appendicitis", "gallstones", "hydronephrosis", "bowel_obstruction", "free_air",
    "fracture",
]
FINDINGS = [c for c in COLUMNS if c != "study_id"]

# Flattening five states onto Stanford's three. Two of these are judgement calls
# and are exposed here rather than buried in code:
#
#   uncertain  -> 1  Stanford's `1` means "the finding was mentioned", and a
#                    hedged mention is still a mention. Their positive prompt
#                    would have matched "may represent a sidebranch IPMN".
#   historical -> 0  A resolved finding is not present now. Stanford's regex had
#                    no way to see this; we do, so we use it.
STATE_TO_CODE = {
    A.PRESENT: 1,
    A.UNCERTAIN: 1,
    A.ABSENT: 0,
    A.HISTORICAL: 0,
    A.NOT_MENTIONED: -1,
}


def build(df: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Returns (drop_in_3_value, full_5_state). `df` is the assembled study table."""
    src = {"pancreatic_atrophy": "panc_atrophy"}
    src.update({f: f"{f}_assertion" for f in C.OTHER_FINDINGS})

    full = pd.DataFrame({"study_id": df.study_id})
    for finding in FINDINGS:
        full[finding] = df[src[finding]].values

    flat = pd.DataFrame({"study_id": df.study_id})
    for finding in FINDINGS:
        flat[finding] = full[finding].map(STATE_TO_CODE).astype("int8")

    return flat[COLUMNS], full[COLUMNS]


def compare_to_original(flat: pd.DataFrame, original_path=None) -> pd.DataFrame:
    """Per-finding comparison against Stanford's file on the studies they share."""
    orig = pd.read_csv(original_path or C.ZERO_SHOT).drop_duplicates("study_id")
    m = flat.merge(orig, on="study_id", suffixes=("_new", "_old"))

    rows = []
    for f in FINDINGS:
        new, old = m[f"{f}_new"], m[f"{f}_old"]
        labelled = old.isin([0, 1])
        rows.append({
            "finding": f,
            "orig_coverage_%": round(100 * labelled.mean(), 1),
            "new_coverage_%": round(100 * new.ne(-1).mean(), 1),
            "orig_pos": int(old.eq(1).sum()),
            "new_pos": int(new.eq(1).sum()),
            "recovered_from_-1": int((old.eq(-1) & new.eq(1)).sum()),
            "agreement_%": (round(100 * (new[labelled] == old[labelled]).mean(), 1)
                            if labelled.any() else None),
        })
    return pd.DataFrame(rows).sort_values("recovered_from_-1", ascending=False)
