"""Resolve the `-1` cells in Stanford's zero-shot file. Nothing else.

Their documentation defines the three values, and the definition is the whole
argument for this module:

    "These labels were generated by applying regex-based matching of zero-shot
     positive and negative prompts to the findings section; therefore, some
     entries marked as missing may in fact correspond to positive or negative
     cases but remain missing when the prompt is not explicitly stated."

    1 = mentioned · 0 = explicitly negated · -1 = not mentioned

So `-1` is a *regex miss*, not a clinical judgement, and 77.6% of the file is
`-1`. Those cells are the defect being repaired here.

Scope is deliberately one-directional. Every `0` and `1` Stanford wrote is
copied through byte-for-byte, even where our extraction disagrees. We do not
have a complete enough rule set to reproduce their file from scratch -- measured,
not assumed: a full re-derivation reproduced only 29,841 of their 135,304
negatives, because their negative prompts read normal-organ statements that a
finding-term matcher cannot see. The right use of our rules is therefore to fill
the gaps in their file, not to replace it.

Two outputs:

* `zero_shot_findings_updated.csv` — their 31 columns, their `1/0/-1` encoding,
                                     diffable against the original directly
* `zero_shot_resolved_cells.csv`   — one row per cell we moved, with the text
                                     span that decided it, so every change is
                                     auditable without rerunning anything
"""
from __future__ import annotations

import pandas as pd

from . import assertion as A
from . import config as C

# Stanford's column order, reproduced exactly so the file stays a drop-in.
COLUMNS = [
    "study_id", "submucosal_edema", "renal_hypodensities", "aortic_valve_calcification",
    "coronary_calcification", "thrombosis", "metastatic_disease", "pancreatic_atrophy",
    "renal_cyst", "osteopenia", "surgically_absent_gallbladder", "atelectasis",
    "abdominal_aortic_aneurysm", "anasarca", "hiatal_hernia", "lymphadenopathy",
    "prostatomegaly", "biliary_ductal_dilation", "cardiomegaly", "splenomegaly",
    "hepatomegaly", "atherosclerosis", "ascites", "pleural_effusion", "hepatic_steatosis",
    "appendicitis", "gallstones", "hydronephrosis", "bowel_obstruction", "free_air",
    "fracture",
]
FINDINGS = [c for c in COLUMNS if c != "study_id"]

# Our five assertion states onto Stanford's three. Two are judgement calls and
# are stated here rather than buried in code:
#
#   uncertain  -> 1  Their `1` means "the finding was mentioned", and a hedged
#                    mention is still a mention; their positive prompt would
#                    have matched "may represent a sidebranch IPMN".
#   historical -> 0  A resolved finding is not present now. Their regex had no
#                    way to see this; ours does.
STATE_TO_CODE = {
    A.PRESENT: 1,
    A.UNCERTAIN: 1,
    A.ABSENT: 0,
    A.HISTORICAL: 0,
    A.NOT_MENTIONED: -1,
}

# `pancreatic_atrophy` is the one finding whose term is organ-agnostic, so it is
# read from the pancreas-scoped concept instead of a whole-report match.
SOURCE = {"pancreatic_atrophy": "panc_atrophy"}
SOURCE.update({f: f"{f}_assertion" for f in C.OTHER_FINDINGS})


def build(df: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Returns (updated_file, per_finding_delta). `df` is the assembled table."""
    out = pd.DataFrame({"study_id": df.study_id})
    rows = []

    for finding in FINDINGS:
        orig = df.get(f"orig_{finding}")
        if orig is None:  # finding absent from the original file entirely
            orig = pd.Series(float("nan"), index=df.index)
        ours = df[SOURCE[finding]].map(STATE_TO_CODE)

        labelled = orig.isin([0, 1])
        # Keep the original wherever it committed to a value; ours elsewhere --
        # including the 214 studies carrying no zero-shot row at all (NaN).
        out[finding] = orig.where(labelled, ours).astype("int8")

        gap = ~labelled
        rows.append({
            "finding": finding,
            "orig_-1": int(gap.sum()),
            "-1_to_1": int((gap & ours.eq(1)).sum()),
            "-1_to_0": int((gap & ours.eq(0)).sum()),
            "still_-1": int((gap & ours.eq(-1)).sum()),
            "orig_pos": int(orig.eq(1).sum()),
            "updated_pos": int(out[finding].eq(1).sum()),
            # Cells where we disagree with a value Stanford committed to. Not
            # applied -- reported, so the size of the disagreement is visible.
            "disagreed_not_applied": int(
                (labelled & orig.eq(0) & ours.eq(1)).sum()
                + (labelled & orig.eq(1) & ours.eq(0)).sum()
            ),
        })

    delta = pd.DataFrame(rows).sort_values("-1_to_1", ascending=False)
    return out[COLUMNS], delta


def resolved_cells(df: pd.DataFrame) -> pd.DataFrame:
    """Long-format audit trail: one row per `-1` cell that moved, with evidence.

    `assertion_state` is kept alongside the flattened value because `1/0/-1`
    cannot express the difference between an asserted finding and a hedged one,
    and between a denial and a resolved-since-prior-study finding.
    """
    ev_col = {f: ("ev_panc_atrophy" if f == "pancreatic_atrophy" else f"ev_{f}")
              for f in FINDINGS}
    out = []

    for finding in FINDINGS:
        orig = df.get(f"orig_{finding}")
        if orig is None:
            orig = pd.Series(float("nan"), index=df.index)
        state = df[SOURCE[finding]]
        ours = state.map(STATE_TO_CODE)

        moved = ~orig.isin([0, 1]) & ours.ne(-1)
        if not moved.any():
            continue
        out.append(pd.DataFrame({
            "study_id": df.loc[moved, "study_id"].values,
            "finding": finding,
            "original": -1,
            "updated": ours[moved].values,
            "assertion_state": state[moved].values,
            "evidence": df.loc[moved, ev_col[finding]].values,
        }))

    res = pd.concat(out, ignore_index=True)
    return res.sort_values(["finding", "updated", "study_id"], ignore_index=True)
